// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/healthz": {
            "get": {
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Проверка состояния сервиса",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/attempts": {
            "post": {
                "security": [
                    {
                        "SessionID": []
                    }
                ],
                "description": "Создаёт новую попытку прохождения сценария.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "attempts"
                ],
                "summary": "Начать попытку",
                "parameters": [
                    {
                        "description": "Данные сценария",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/httptransport.StartAttemptRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/training.StartResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httptransport.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httptransport.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httptransport.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httptransport.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/attempts/{attemptID}/choice": {
            "post": {
                "security": [
                    {
                        "SessionID": []
                    }
                ],
                "description": "Отправляет выбор пользователя для текущей сцены.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "attempts"
                ],
                "summary": "Сделать выбор в попытке",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID попытки",
                        "name": "attemptID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Выбор пользователя",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/httptransport.ChoiceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/training.ChoiceResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httptransport.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httptransport.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httptransport.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/httptransport.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/httptransport.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httptransport.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/attempts/{attemptID}/summary": {
            "get": {
                "security": [
                    {
                        "SessionID": []
                    }
                ],
                "description": "Возвращает итоговую информацию по попытке пользователя.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "attempts"
                ],
                "summary": "Получить результат попытки",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID попытки",
                        "name": "attemptID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/training.SummaryResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httptransport.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httptransport.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httptransport.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httptransport.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/auth/login": {
            "post": {
                "description": "Выполняет вход по email и паролю и создаёт сессию.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Вход в систему",
                "parameters": [
                    {
                        "description": "Учётные данные",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/httptransport.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httptransport.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httptransport.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httptransport.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/auth/logout": {
            "post": {
                "security": [
                    {
                        "SessionID": []
                    }
                ],
                "description": "Завершает текущую сессию.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Выход из системы",
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httptransport.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httptransport.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/auth/register": {
            "post": {
                "description": "Создаёт пользователя и связанную с ним сессию.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Регистрация пользователя",
                "parameters": [
                    {
                        "description": "Данные для регистрации",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/httptransport.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/httptransport.RegisterResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httptransport.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/httptransport.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httptransport.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/progress": {
            "get": {
                "security": [
                    {
                        "SessionID": []
                    }
                ],
                "description": "Возвращает общий прогресс текущего авторизованного пользователя по сценариям.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "progress"
                ],
                "summary": "Получить прогресс пользователя",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httptransport.progressResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httptransport.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httptransport.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/httptransport.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/scenarios": {
            "get": {
                "security": [
                    {
                        "SessionID": []
                    }
                ],
                "description": "Возвращает доступные пользователю сценарии.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "training"
                ],
                "summary": "Получить список сценариев",
                "parameters": [
                    {
                        "enum": [
                            "buyer",
                            "seller"
                        ],
                        "type": "string",
                        "description": "Роль пользователя",
                        "name": "role",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httptransport.ScenariosResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httptransport.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httptransport.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httptransport.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/users/me": {
            "get": {
                "security": [
                    {
                        "SessionID": []
                    }
                ],
                "description": "Возвращает данные пользователя, связанного с текущей сессией.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Получить текущего пользователя",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httptransport.UserResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httptransport.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httptransport.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.Attachment": {
            "type": "object",
            "properties": {
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "domain.Author": {
            "type": "string",
            "enum": [
                "counterpart",
                "system",
                "user"
            ],
            "x-enum-comments": {
                "AuthorCounterpart": "собеседник (потенциальный мошенник)",
                "AuthorSystem": "служебная вставка",
                "AuthorUser": "реплика самого пользователя"
            },
            "x-enum-descriptions": [
                "собеседник (потенциальный мошенник)",
                "служебная вставка",
                "реплика самого пользователя"
            ],
            "x-enum-varnames": [
                "AuthorCounterpart",
                "AuthorSystem",
                "AuthorUser"
            ]
        },
        "domain.Counterpart": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "rating": {
                    "type": "number"
                },
                "registered": {
                    "type": "string"
                },
                "reviews": {
                    "type": "integer"
                }
            }
        },
        "domain.Ending": {
            "type": "object",
            "properties": {
                "outcome": {
                    "$ref": "#/definitions/domain.Outcome"
                },
                "text": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "domain.FlagInfo": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "text": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "domain.Listing": {
            "type": "object",
            "properties": {
                "image": {
                    "description": "TODO: решить вопрос с image",
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "price": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "domain.Message": {
            "type": "object",
            "properties": {
                "attachment": {
                    "$ref": "#/definitions/domain.Attachment"
                },
                "author": {
                    "$ref": "#/definitions/domain.Author"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "domain.Outcome": {
            "type": "string",
            "enum": [
                "safe",
                "partial",
                "scammed"
            ],
            "x-enum-varnames": [
                "OutcomeSafe",
                "OutcomePartial",
                "OutcomeScammed"
            ]
        },
        "domain.Role": {
            "type": "string",
            "enum": [
                "buyer",
                "seller"
            ],
            "x-enum-varnames": [
                "RoleBuyer",
                "RoleSeller"
            ]
        },
        "domain.Verdict": {
            "type": "string",
            "enum": [
                "safe",
                "risky",
                "fatal"
            ],
            "x-enum-comments": {
                "VerdictFatal": "fatal — точка невозврата",
                "VerdictRisky": "risky — рискованное, но не фатальное",
                "VerdictSafe": "safe  — безопасное действие;"
            },
            "x-enum-descriptions": [
                "safe  — безопасное действие;",
                "risky — рискованное, но не фатальное",
                "fatal — точка невозврата"
            ],
            "x-enum-varnames": [
                "VerdictSafe",
                "VerdictRisky",
                "VerdictFatal"
            ]
        },
        "httptransport.ChoiceRequest": {
            "type": "object",
            "required": [
                "expected_revision",
                "option_id",
                "scene_id"
            ],
            "properties": {
                "expected_revision": {
                    "type": "integer",
                    "minimum": 0
                },
                "option_id": {
                    "type": "string"
                },
                "scene_id": {
                    "type": "string"
                }
            }
        },
        "httptransport.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "httptransport.LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "maxLength": 254
                },
                "password": {
                    "type": "string",
                    "maxLength": 72,
                    "minLength": 8
                }
            }
        },
        "httptransport.LoginResponse": {
            "type": "object",
            "properties": {
                "sessionId": {
                    "type": "string"
                }
            }
        },
        "httptransport.RegisterRequest": {
            "type": "object",
            "required": [
                "email",
                "nickname",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "maxLength": 254
                },
                "nickname": {
                    "type": "string",
                    "maxLength": 30,
                    "minLength": 3
                },
                "password": {
                    "type": "string",
                    "maxLength": 72,
                    "minLength": 8
                }
            }
        },
        "httptransport.RegisterResponse": {
            "type": "object",
            "properties": {
                "sessionId": {
                    "type": "string"
                }
            }
        },
        "httptransport.ScenariosResponse": {
            "type": "object",
            "properties": {
                "scenarios": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/training.ScenarioCard"
                    }
                }
            }
        },
        "httptransport.StartAttemptRequest": {
            "type": "object",
            "required": [
                "scenario_id"
            ],
            "properties": {
                "scenario_id": {
                    "type": "string"
                }
            }
        },
        "httptransport.UserResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                }
            }
        },
        "httptransport.completedAttemptResultResponse": {
            "type": "object",
            "properties": {
                "attemptId": {
                    "type": "string"
                },
                "completedAt": {
                    "type": "string"
                },
                "outcome": {
                    "$ref": "#/definitions/domain.Outcome"
                },
                "score": {
                    "$ref": "#/definitions/httptransport.scoreResponse"
                }
            }
        },
        "httptransport.progressResponse": {
            "type": "object",
            "properties": {
                "completedScenarios": {
                    "type": "integer"
                },
                "completionPercent": {
                    "type": "integer"
                },
                "passedPercent": {
                    "type": "integer"
                },
                "passedScenarios": {
                    "type": "integer"
                },
                "roleComparison": {
                    "$ref": "#/definitions/httptransport.roleComparisonResponse"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/httptransport.roleProgressResponse"
                    }
                },
                "totalScenarios": {
                    "type": "integer"
                }
            }
        },
        "httptransport.roleComparisonResponse": {
            "type": "object",
            "properties": {
                "completionPercentDelta": {
                    "type": "integer"
                },
                "passedPercentDelta": {
                    "type": "integer"
                }
            }
        },
        "httptransport.roleProgressResponse": {
            "type": "object",
            "properties": {
                "completedScenarios": {
                    "type": "integer"
                },
                "completionPercent": {
                    "type": "integer"
                },
                "passedPercent": {
                    "type": "integer"
                },
                "passedScenarios": {
                    "type": "integer"
                },
                "role": {
                    "$ref": "#/definitions/domain.Role"
                },
                "scenarios": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/httptransport.scenarioProgressResponse"
                    }
                },
                "totalScenarios": {
                    "type": "integer"
                }
            }
        },
        "httptransport.scenarioProgressResponse": {
            "type": "object",
            "properties": {
                "activeAttemptId": {
                    "type": "string"
                },
                "attemptsCount": {
                    "type": "integer"
                },
                "bestScore": {
                    "$ref": "#/definitions/httptransport.scoreResponse"
                },
                "completed": {
                    "type": "boolean"
                },
                "firstSafeAttempt": {
                    "$ref": "#/definitions/httptransport.completedAttemptResultResponse"
                },
                "improvementPercentPoints": {
                    "type": "integer"
                },
                "initialScore": {
                    "$ref": "#/definitions/httptransport.scoreResponse"
                },
                "latestScore": {
                    "$ref": "#/definitions/httptransport.scoreResponse"
                },
                "passed": {
                    "type": "boolean"
                },
                "recentAttempts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/httptransport.completedAttemptResultResponse"
                    }
                },
                "scenarioSlug": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "trend": {
                    "type": "string"
                }
            }
        },
        "httptransport.scoreResponse": {
            "type": "object",
            "properties": {
                "maxPoints": {
                    "type": "integer"
                },
                "percent": {
                    "type": "integer"
                },
                "points": {
                    "type": "integer"
                }
            }
        },
        "training.ChoiceResult": {
            "type": "object",
            "properties": {
                "feedback": {
                    "$ref": "#/definitions/training.Feedback"
                },
                "finished": {
                    "type": "boolean"
                },
                "next_scene": {
                    "$ref": "#/definitions/training.ScenePayload"
                },
                "reaction": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Message"
                    }
                },
                "revision": {
                    "type": "integer"
                },
                "summary": {
                    "$ref": "#/definitions/training.SummaryResult"
                }
            }
        },
        "training.Feedback": {
            "type": "object",
            "properties": {
                "text": {
                    "type": "string"
                },
                "verdict": {
                    "$ref": "#/definitions/domain.Verdict"
                }
            }
        },
        "training.OptionPayload": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "training.ScenarioCard": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "difficulty": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/domain.Role"
                },
                "slug": {
                    "type": "string"
                },
                "stats": {
                    "$ref": "#/definitions/training.ScenarioStats"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "training.ScenarioStats": {
            "type": "object",
            "properties": {
                "attempts_count": {
                    "type": "integer"
                },
                "best_score": {
                    "type": "integer"
                }
            }
        },
        "training.ScenePayload": {
            "type": "object",
            "properties": {
                "intro": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Message"
                    }
                },
                "options": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/training.OptionPayload"
                    }
                },
                "prompt": {
                    "type": "string"
                },
                "scene_id": {
                    "type": "string"
                }
            }
        },
        "training.StartResult": {
            "type": "object",
            "properties": {
                "attempt_id": {
                    "type": "string"
                },
                "counterpart": {
                    "$ref": "#/definitions/domain.Counterpart"
                },
                "listing": {
                    "$ref": "#/definitions/domain.Listing"
                },
                "role": {
                    "$ref": "#/definitions/domain.Role"
                },
                "scene": {
                    "$ref": "#/definitions/training.ScenePayload"
                },
                "scenes_total": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "training.SummaryResult": {
            "type": "object",
            "properties": {
                "delta_vs_previous": {
                    "type": "integer"
                },
                "ending": {
                    "$ref": "#/definitions/domain.Ending"
                },
                "missed_flags": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.FlagInfo"
                    }
                },
                "outcome": {
                    "$ref": "#/definitions/domain.Outcome"
                },
                "score": {
                    "type": "integer"
                },
                "steps_total": {
                    "type": "integer"
                },
                "takeaway": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "SessionID": {
            "type": "apiKey",
            "name": "X-Session-ID",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "AntiScam API",
	Description:      "API сервиса AntiScam.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
